[project]
name = "python-geometry"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "olatejulian", email = "julian.lf.olate@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.16,<0.10.0"]
build-backend = "uv_build"
